
version: 0.2
# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

#################################
# Runtime Environment Variables #
#################################

# env:
#   variables:
#     key: "value"
#     key: "value"
#   parameter-store:
#     key: "value"
#     key: "value"

phases:
  install:
    runtime-versions:	
      nodejs: 10
      java: corretto8
      python: 3.7
      docker: 18
    commands:
      # Use Install phase to install packages or any pre-reqs you may need throughout the build (e.g. dev deps, security checks, etc.)
      - echo "Install node and npm and sam"
      - pip3 install --upgrade aws-sam-cli 
      - cd simpleApp
      - cd ..
  build:
    commands:
      - echo "Build start on `date`"
      - echo `Builddd start on date`
      - echo CODEBUILD_BUILD_IMAGE=$CODEBUILD_BUILD_IMAGE
      - echo CODEBUILD_SOURCE_REPO_URL=$CODEBUILD_SOURCE_REPO_URL
      - echo CODEBUILD_SRC_DIR=$CODEBUILD_SRC_DIR
      - echo BUILD_OUTPUT_BUCKET=$BUILD_OUTPUT_BUCKET
      - cd simpleApp
      - ls
      - java -version
      - mvn package -DskipTests
      - cd target
      - ls
      - cd ..
      - sam package --s3-bucket $BUILD_OUTPUT_BUCKET --template-file template.yml --output-template-file packaged.yml
  post_build:
    commands:
      # Use Post Build for notifications, git tags and any further customization after build
      # - echo "[Post-Build phase]"
      - echo "SAM packaging completed on `date`"

##################################
# Build Artifacts to be uploaded #
##################################

artifacts:
  files:
    # list of local files relative to this build environment that will be added to the final artifact (zip)
    - simpleApp/packaged.yml
  discard-paths: yes

#########################################
# Cache local files for subsequent runs #
#########################################

cache:
  paths:
  # List of path that CodeBuild will upload to S3 Bucket and use in subsequent runs to speed up Builds
  # - '/root/.cache/pip'
