AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

# Parameters definitions
Parameters: 
  MyEnvironment: 
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - staging
      - prod
    Description: Environment of this stack of resources

Mappings:
  ResourcesName:
    dev:
      tableName: MyDynamoDBTable-dev
    staging:
      tableName: MyDynamoDBTable-staging
    prod:
      tableName: MyDynamoDBTable-prod

# Global information for all the functions
Globals:
  Function:
    Runtime: java8
    MemorySize: 256
    Timeout: 100

Resources:

  # Basic definitions for my API Gateway
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref MyEnvironment

  # A function with the most commont attributes
  MySimpleFunction: 
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: mySimpleFunction.handler
      Runtime: java8
      CodeUri: target/aws-sam-java-rest-1.0.0.jar
      Handler: com.jmbo.covid19.lambda::handleRequest
      Events:
        MySimpleFunctionAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /simple
            Method: GET

Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  ApiId:
    Description: "API ID"
    Value: !Ref MyApi

  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/'